Nama : Iqbal Al Hafidzu Rahman
NPM : 2117051019
Kelas : D

Sumber dataset : https://data.world/data-society/pima-indians-diabetes-database

In [1346]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [1347]:
# load data dari github

dataset = pd.read_csv("https://raw.githubusercontent.com/Iqbalalh/prediksi-diabetes/main/diabetes.csv")
dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

Preprocessing

In [1348]:
# drop skin thickness untuk efisiensi
df = dataset.drop(['SkinThickness'], axis = 1)

In [1349]:
df

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,0,33.6,0.627,50,1
1,1,85,66,0,26.6,0.351,31,0
2,8,183,64,0,23.3,0.672,32,1
3,1,89,66,94,28.1,0.167,21,0
4,0,137,40,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
763,10,101,76,180,32.9,0.171,63,0
764,2,122,70,0,36.8,0.340,27,0
765,5,121,72,112,26.2,0.245,30,0
766,1,126,60,0,30.1,0.349,47,1
767,1,93,70,0,30.4,0.315,23,0

Train Test Split

In [1350]:
# split train dan test data
df_train, df_test = train_test_split(df, test_size=0.4, random_state=82)

In [1351]:
df_train

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
225,1,87,78,32,34.6,0.101,22,0
204,6,103,72,190,37.7,0.324,55,0
63,2,141,58,128,25.4,0.699,24,0
674,8,91,82,0,35.6,0.587,68,0
124,0,113,76,0,33.3,0.278,23,1
...,...,...,...,...,...,...,...,...
349,5,0,80,0,41.0,0.346,37,1
411,1,112,72,176,34.4,0.528,25,0
767,1,93,70,0,30.4,0.315,23,0
450,1,82,64,95,21.2,0.415,23,0
131,9,122,56,0,33.3,1.114,33,1

In [1352]:
# memisahkan fitur dengan variabel yg dijadikan target

X_train = df_train.drop('Outcome', axis=1)
y_train = df_train['Outcome']
X_test = df_test.drop('Outcome', axis=1)
y_test = df_test['Outcome']

In [1353]:
# pre processing dengan scaling dataset menggunakan minmaxscaler

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [1354]:
# seleksi fitur menggunakan chi squared test

selector = SelectKBest(chi2, k=7)
X_train_new = selector.fit_transform(X_train_scaled, y_train)
X_test_new = selector.transform(X_test_scaled)

In [1355]:
# fitur yang akan dipakai untuk training model

X_train.columns[selector.get_support()]

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'Insulin', 'BMI',
       'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

Model menggunakan Logistic Regression

In [1356]:
# model

prediksi_diabetes = LogisticRegression(penalty='l2', random_state=45645645, solver='saga')
prediksi_diabetes.fit(X_train_new, y_train)

LogisticRegression(random_state=45645645, solver='saga')

Evaluasi

In [1357]:
# accuracy

accuracy = prediksi_diabetes.score(X_test_new, y_test)
accuracy

0.8181818181818182

Prediksi data dummy

In [1358]:
# load data dummy yang dibuat

dummy = pd.read_csv('https://raw.githubusercontent.com/Iqbalalh/prediksi-diabetes/main/dummy_diabetes.csv')
X_test = dummy

In [1359]:
# prediksi data dummy menggunakan model prediksi_diabetes

y_pred = prediksi_diabetes.predict(X_test.values)
df_pred = dummy
dummy['Outcome'] = y_pred
dummy

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,0.0,33.6,0.627,50,1
1,0,60,75,0.0,26.6,0.000,20,1
2,0,137,40,43.1,23.3,2.288,45,1
3,8,155,80,0.0,26.6,0.154,66,1
4,1,99,62,94.0,23.5,0.866,25,1